---
title: "Baseball yay"
subtitle: "Programming in Statistics - Project"
author: "Vilsmeier Johannes, Sterneder Florian, Schaub Andrea"
date: '`r Sys.Date()`'
output:
  html_document:
    code_folding: show
    theme: cosmo
    highlight: tango
    number_sections: true
    toc: true
    toc_float: yes
    fig_width: 7
    fig_height: 4.5
---

```{r hide=T, warning=F, message=F}
library(knitr)
opts_chunk$set(echo = TRUE,
               collapse = FALSE,
               comment = "",
               strip.white = TRUE,
               warning = FALSE,
               messages = FALSE,
               out.width = "70%",
               fig.align = "center")
library(tidyverse)
library(zeallot)

setup <- list()

setup$files <- c("AllstarFull","Appearances","AwardsManagers","AwardsPlayers","AwardsShareManagers","AwardsSharePlayers","CollegePlaying","HallOfFame","Managers","ManagersHalf","People","Teams")

# read all files from setup$files
setup$data %<-% 
  (map(setup$files, function(f){
    return (read_csv(
      paste("./data/",f,".csv",sep=""), col_names=T)
    )})
  )

# assigns setup$data files the names of setup$files
walk2(setup$files, setup$data, assign,envir=globalenv())
```

```{r}
People
```
